### ISSUE TITLE
Arch AUR link is a 404

### ISSUE THREAD

**Issue by not-reed** [alephium/awesome-alephium#50]
https://aur.archlinux.org/packages/alephium-wallet-bin no longer exists it seems
![image](https://github.com/alephium/awesome-alephium/assets/86171134/94fc9267-9d66-4d69-8861-588439d13856)

![image](https://github.com/alephium/awesome-alephium/assets/86171134/de31a75e-07d7-47b7-b1f2-0a8d1545c2c6)

**Comment by MaudSimon** [comment]
https://discord.com/channels/747741246667227157/1188211400288522342/1189261043650793615

I think I need to update based on that.

**Comment by MaudSimon** [comment]
Edited link.
